#include <Rcpp.h>
#include <cmath>

// detect event function
// calculate backtest performance
// backtest performance becomes an indicator
// pos is different; pos is vector generated by a strategy
// when we are doing backtest of event, it is a binary pos for single event
// so you will classify it into events of certain days after bullish/bearish cross
// or you can map atr into bins; then you can provide a combination of last several bins; you will have thousand of types of events here; so be careful to choose suitable event classifications

// you also need to discuss the standard format of DT (datetime, open, high, low, close)
// Exponential Moving Average (EMA)
//
// EMA extends the simple moving average (SMA) by assigning exponentially
// decaying weights to past observations. Newer values receive higher weight
// through a decay parameter alpha, where 0 < alpha <= 1.
//
// The recursive definition is:
//   ema_t = alpha * x_t + (1 - alpha) * ema_{t-1}
//
// As a result, EMA is an autocorrelated time series and requires an initial
// seed value. Different seeding strategies lead to different early behavior.
//
// Relationship to SMA and time-series models:
//   - SMA is a finite-window MA(n) process.
//   - EMA corresponds to an infinite-memory AR(1)-type filter with decay
//     governed by alpha.
//
// Seeding options:
//   - seed_mode = 0: seed using SMA(n), with NA padding before index (n - 1).
//     This matches the default behavior of TTR::EMA.
//   - seed_mode = 1: seed using the first observation x[0], producing no
//     leading NA values.
//
// By default, technical analysis libraries use:
//   alpha = 2 / (n + 1)
// which is recommended for comparability with common TA tools.
//
// Alternative choices of alpha are also supported, including:
//   - Wilder’s smoothing: alpha = 1 / n (used for RSI, ATR, ADX)
//   - Half-life formulation: alpha = 1 - exp(-log(2) / half_life),
//     where half_life is a chosen number of steps for the EMA weight to decay by 50%
//   - Time-constant formulation: alpha = 1 - exp(-1 / tau),
//     where tau is a chosen continuous-time decay constant
//
// As with SMA, the EMA value at index i is defined only after x[i] is observed.
// The handling of early values depends on the chosen seeding strategy.

// Strategyr package is for generating strategy order for Stocks, Bonds, Derivatives, and Crypto assets;
// This needs to be moved to a header part; so we can reuse this function in the future
// It is suggested to have a .h file including ema_core/ema_cpp also; but be careful not to put too many nuances in rcpp part and unseen by R users
// And I don't think we need to let RCPP overdoing its job if data.table and plain R vector computation can achieve the same purpose without sacrificing too much efficiency
// we are not simply replicating a TA package because we view all the indicators an outcome of certain strategy's weighted backtesting output
// Thus it allows our package to have a very unique perspective of all the measures and have more innovative indicators
// Our package will have event class of measures, which are binary variables different from indicator and position; through a normal post-event test, we can see the statitics of strategy of holding a position linked to the event for different periods; it is an intermediate outcome for evaluation; it is part of the workflow of horning strategy orders
// pos_ family generates vector position over time, which is convenient for vector-type fast backtesting (not a simulation backtesting), so it is also not our final output
// ord_ and portf_ families are the final outputs of this package; the former determines what postion and weight of allocated budget for certain security in current moment; the latter is for determine the optimal weights across assets
// Utility: sigmoid function
inline double sigmoid(double z) {
  return 1.0 / (1.0 + std::exp(-z));
}

// all rcpp functions should only use past information, so they can also be used in live trading


// [[Rcpp::export]]
Rcpp::DataFrame twoline_cross(const Rcpp::NumericVector &fast_line, const Rcpp::NumericVector &slow_line)
{
  const int n = fast_line.size();
  if (slow_line.size() != n) {
    Rcpp::stop("two line vector must have the same length.");
  }

  Rcpp::IntegerVector bars_since_cross(n);
  Rcpp::NumericVector cycle_type(n, NA_REAL);    // 1 = up, -1 = down

  int last_cross       = NA_INTEGER;
  int last_cross_type  = 0;   // 1 = up, -1 = down, 0 = none yet

  for (int i = 0; i < n; ++i) {

    const double fast = fast_line[i];
    const double slow = slow_line[i];

    if (i > 0) {
      const double fast_prev = fast_line[i - 1];
      const double slow_prev = slow_line[i - 1];

      const bool valid_prev =
        !Rcpp::NumericVector::is_na(fast_prev) &&
        !Rcpp::NumericVector::is_na(slow_prev);

      const bool valid_cur =
        !Rcpp::NumericVector::is_na(fast) &&
        !Rcpp::NumericVector::is_na(slow);

      bool crossed_up   = false;
      bool crossed_down = false;

      if (valid_prev && valid_cur) {
        crossed_up   = (fast_prev < slow_prev) && (fast >= slow);
        crossed_down = (fast_prev > slow_prev) && (fast <= slow);
      }

      if (crossed_up || crossed_down) {
        last_cross = i;
        bars_since_cross[i] = 0;
        last_cross_type = crossed_up ? 1 : -1;
      } else if (last_cross != NA_INTEGER) {
        if (valid_cur) {
          bars_since_cross[i] = i - last_cross;
        } else {
          bars_since_cross[i] = NA_INTEGER;
        }
      } else {
        bars_since_cross[i] = NA_INTEGER;
      }

    } else {
      bars_since_cross[i] = NA_INTEGER;
    }

    cycle_type[i] = last_cross_type;
	}

  return Rcpp::DataFrame::create(

    Rcpp::_["cycle_type"] = cycle_type,
    Rcpp::_["bsc"] = bars_since_cross

  );
}