// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// bbands_cpp
List bbands_cpp(NumericVector x, int n, double sd);
RcppExport SEXP _strategyr_bbands_cpp(SEXP xSEXP, SEXP nSEXP, SEXP sdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type sd(sdSEXP);
    rcpp_result_gen = Rcpp::wrap(bbands_cpp(x, n, sd));
    return rcpp_result_gen;
END_RCPP
}
// bbands_cpp2
List bbands_cpp2(NumericVector x, int n, double sd);
RcppExport SEXP _strategyr_bbands_cpp2(SEXP xSEXP, SEXP nSEXP, SEXP sdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type sd(sdSEXP);
    rcpp_result_gen = Rcpp::wrap(bbands_cpp2(x, n, sd));
    return rcpp_result_gen;
END_RCPP
}
// cluster_price_levels
Rcpp::DataFrame cluster_price_levels(const Rcpp::NumericVector& level, const Rcpp::NumericVector& score, const Rcpp::NumericVector& tolerance, int score_mode);
RcppExport SEXP _strategyr_cluster_price_levels(SEXP levelSEXP, SEXP scoreSEXP, SEXP toleranceSEXP, SEXP score_modeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type level(levelSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type score(scoreSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type tolerance(toleranceSEXP);
    Rcpp::traits::input_parameter< int >::type score_mode(score_modeSEXP);
    rcpp_result_gen = Rcpp::wrap(cluster_price_levels(level, score, tolerance, score_mode));
    return rcpp_result_gen;
END_RCPP
}
// merge_overlapping_zones
Rcpp::DataFrame merge_overlapping_zones(const Rcpp::NumericVector& zone_low, const Rcpp::NumericVector& zone_high, const Rcpp::NumericVector& zone_score, const Rcpp::IntegerVector& zone_n, double gap_tolerance, int score_mode);
RcppExport SEXP _strategyr_merge_overlapping_zones(SEXP zone_lowSEXP, SEXP zone_highSEXP, SEXP zone_scoreSEXP, SEXP zone_nSEXP, SEXP gap_toleranceSEXP, SEXP score_modeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type zone_low(zone_lowSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type zone_high(zone_highSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type zone_score(zone_scoreSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type zone_n(zone_nSEXP);
    Rcpp::traits::input_parameter< double >::type gap_tolerance(gap_toleranceSEXP);
    Rcpp::traits::input_parameter< int >::type score_mode(score_modeSEXP);
    rcpp_result_gen = Rcpp::wrap(merge_overlapping_zones(zone_low, zone_high, zone_score, zone_n, gap_tolerance, score_mode));
    return rcpp_result_gen;
END_RCPP
}
// detect_cycles_now_cpp
DataFrame detect_cycles_now_cpp(const DataFrame& pivots, int min_backward_bars, int min_stable_pivots);
RcppExport SEXP _strategyr_detect_cycles_now_cpp(SEXP pivotsSEXP, SEXP min_backward_barsSEXP, SEXP min_stable_pivotsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const DataFrame& >::type pivots(pivotsSEXP);
    Rcpp::traits::input_parameter< int >::type min_backward_bars(min_backward_barsSEXP);
    Rcpp::traits::input_parameter< int >::type min_stable_pivots(min_stable_pivotsSEXP);
    rcpp_result_gen = Rcpp::wrap(detect_cycles_now_cpp(pivots, min_backward_bars, min_stable_pivots));
    return rcpp_result_gen;
END_RCPP
}
// detect_main_cycles_cpp
Rcpp::DataFrame detect_main_cycles_cpp(const Rcpp::IntegerVector& idx, const Rcpp::NumericVector& price, const Rcpp::NumericVector& datetime, int cycle_N);
RcppExport SEXP _strategyr_detect_main_cycles_cpp(SEXP idxSEXP, SEXP priceSEXP, SEXP datetimeSEXP, SEXP cycle_NSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type idx(idxSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type price(priceSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type datetime(datetimeSEXP);
    Rcpp::traits::input_parameter< int >::type cycle_N(cycle_NSEXP);
    rcpp_result_gen = Rcpp::wrap(detect_main_cycles_cpp(idx, price, datetime, cycle_N));
    return rcpp_result_gen;
END_RCPP
}
// get_now_fresh_main_cycles_cpp
DataFrame get_now_fresh_main_cycles_cpp(const DataFrame& pivots, int min_backward_bars, int min_stable_pivots);
RcppExport SEXP _strategyr_get_now_fresh_main_cycles_cpp(SEXP pivotsSEXP, SEXP min_backward_barsSEXP, SEXP min_stable_pivotsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const DataFrame& >::type pivots(pivotsSEXP);
    Rcpp::traits::input_parameter< int >::type min_backward_bars(min_backward_barsSEXP);
    Rcpp::traits::input_parameter< int >::type min_stable_pivots(min_stable_pivotsSEXP);
    rcpp_result_gen = Rcpp::wrap(get_now_fresh_main_cycles_cpp(pivots, min_backward_bars, min_stable_pivots));
    return rcpp_result_gen;
END_RCPP
}
// twoline_cross
Rcpp::DataFrame twoline_cross(const Rcpp::NumericVector& fast_line, const Rcpp::NumericVector& slow_line);
RcppExport SEXP _strategyr_twoline_cross(SEXP fast_lineSEXP, SEXP slow_lineSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type fast_line(fast_lineSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type slow_line(slow_lineSEXP);
    rcpp_result_gen = Rcpp::wrap(twoline_cross(fast_line, slow_line));
    return rcpp_result_gen;
END_RCPP
}
// event_score
Rcpp::DataFrame event_score(const Rcpp::IntegerVector& event_id, const Rcpp::NumericVector& future_outcome, double h, double coef);
RcppExport SEXP _strategyr_event_score(SEXP event_idSEXP, SEXP future_outcomeSEXP, SEXP hSEXP, SEXP coefSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type event_id(event_idSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type future_outcome(future_outcomeSEXP);
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    Rcpp::traits::input_parameter< double >::type coef(coefSEXP);
    rcpp_result_gen = Rcpp::wrap(event_score(event_id, future_outcome, h, coef));
    return rcpp_result_gen;
END_RCPP
}
// fib_all_cpp
List fib_all_cpp(double trend_start, double trend_end, NumericVector retr_levels, NumericVector ext_levels);
RcppExport SEXP _strategyr_fib_all_cpp(SEXP trend_startSEXP, SEXP trend_endSEXP, SEXP retr_levelsSEXP, SEXP ext_levelsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type trend_start(trend_startSEXP);
    Rcpp::traits::input_parameter< double >::type trend_end(trend_endSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type retr_levels(retr_levelsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ext_levels(ext_levelsSEXP);
    rcpp_result_gen = Rcpp::wrap(fib_all_cpp(trend_start, trend_end, retr_levels, ext_levels));
    return rcpp_result_gen;
END_RCPP
}
// get_fib_ladder_index_cpp
Rcpp::IntegerVector get_fib_ladder_index_cpp(const Rcpp::NumericVector& close, const Rcpp::NumericVector& bg, const Rcpp::NumericVector& ed, int center_idx);
RcppExport SEXP _strategyr_get_fib_ladder_index_cpp(SEXP closeSEXP, SEXP bgSEXP, SEXP edSEXP, SEXP center_idxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type close(closeSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type bg(bgSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type ed(edSEXP);
    Rcpp::traits::input_parameter< int >::type center_idx(center_idxSEXP);
    rcpp_result_gen = Rcpp::wrap(get_fib_ladder_index_cpp(close, bg, ed, center_idx));
    return rcpp_result_gen;
END_RCPP
}
// detect_pivots_cpp
Rcpp::DataFrame detect_pivots_cpp(const Rcpp::NumericVector& high, const Rcpp::NumericVector& low, const Rcpp::NumericVector& datetime, int span, Rcpp::Nullable<int> latest_n, bool refined, double min_swing);
RcppExport SEXP _strategyr_detect_pivots_cpp(SEXP highSEXP, SEXP lowSEXP, SEXP datetimeSEXP, SEXP spanSEXP, SEXP latest_nSEXP, SEXP refinedSEXP, SEXP min_swingSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type high(highSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type low(lowSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type datetime(datetimeSEXP);
    Rcpp::traits::input_parameter< int >::type span(spanSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<int> >::type latest_n(latest_nSEXP);
    Rcpp::traits::input_parameter< bool >::type refined(refinedSEXP);
    Rcpp::traits::input_parameter< double >::type min_swing(min_swingSEXP);
    rcpp_result_gen = Rcpp::wrap(detect_pivots_cpp(high, low, datetime, span, latest_n, refined, min_swing));
    return rcpp_result_gen;
END_RCPP
}
// rolling_sum
Rcpp::NumericVector rolling_sum(const Rcpp::NumericVector& x, int n);
RcppExport SEXP _strategyr_rolling_sum(SEXP xSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(rolling_sum(x, n));
    return rcpp_result_gen;
END_RCPP
}
// rolling_mean
Rcpp::NumericVector rolling_mean(const Rcpp::NumericVector& x, int n);
RcppExport SEXP _strategyr_rolling_mean(SEXP xSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(rolling_mean(x, n));
    return rcpp_result_gen;
END_RCPP
}
// rolling_sd
Rcpp::NumericVector rolling_sd(const Rcpp::NumericVector& x, int n, bool sample);
RcppExport SEXP _strategyr_rolling_sd(SEXP xSEXP, SEXP nSEXP, SEXP sampleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< bool >::type sample(sampleSEXP);
    rcpp_result_gen = Rcpp::wrap(rolling_sd(x, n, sample));
    return rcpp_result_gen;
END_RCPP
}
// ema_ttr_fixed_step
Rcpp::NumericVector ema_ttr_fixed_step(const Rcpp::NumericVector& x, int n, bool wilder);
RcppExport SEXP _strategyr_ema_ttr_fixed_step(SEXP xSEXP, SEXP nSEXP, SEXP wilderSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< bool >::type wilder(wilderSEXP);
    rcpp_result_gen = Rcpp::wrap(ema_ttr_fixed_step(x, n, wilder));
    return rcpp_result_gen;
END_RCPP
}
// ema_tau_fixed_step
Rcpp::NumericVector ema_tau_fixed_step(const Rcpp::NumericVector& x, double tau);
RcppExport SEXP _strategyr_ema_tau_fixed_step(SEXP xSEXP, SEXP tauSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    rcpp_result_gen = Rcpp::wrap(ema_tau_fixed_step(x, tau));
    return rcpp_result_gen;
END_RCPP
}
// ema_tau_irregular
Rcpp::NumericVector ema_tau_irregular(const Rcpp::NumericVector& t, const Rcpp::NumericVector& x, double tau);
RcppExport SEXP _strategyr_ema_tau_irregular(SEXP tSEXP, SEXP xSEXP, SEXP tauSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type t(tSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    rcpp_result_gen = Rcpp::wrap(ema_tau_irregular(t, x, tau));
    return rcpp_result_gen;
END_RCPP
}
// zones_quantile_fixed_cpp
DataFrame zones_quantile_fixed_cpp(NumericVector high, NumericVector low, int window);
RcppExport SEXP _strategyr_zones_quantile_fixed_cpp(SEXP highSEXP, SEXP lowSEXP, SEXP windowSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type high(highSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type low(lowSEXP);
    Rcpp::traits::input_parameter< int >::type window(windowSEXP);
    rcpp_result_gen = Rcpp::wrap(zones_quantile_fixed_cpp(high, low, window));
    return rcpp_result_gen;
END_RCPP
}
// zones_quantile_dyn_cpp
DataFrame zones_quantile_dyn_cpp(NumericVector high, NumericVector low, NumericVector close, NumericVector atr14, double mom_threshold, int min_window, int max_window);
RcppExport SEXP _strategyr_zones_quantile_dyn_cpp(SEXP highSEXP, SEXP lowSEXP, SEXP closeSEXP, SEXP atr14SEXP, SEXP mom_thresholdSEXP, SEXP min_windowSEXP, SEXP max_windowSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type high(highSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type low(lowSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type close(closeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type atr14(atr14SEXP);
    Rcpp::traits::input_parameter< double >::type mom_threshold(mom_thresholdSEXP);
    Rcpp::traits::input_parameter< int >::type min_window(min_windowSEXP);
    Rcpp::traits::input_parameter< int >::type max_window(max_windowSEXP);
    rcpp_result_gen = Rcpp::wrap(zones_quantile_dyn_cpp(high, low, close, atr14, mom_threshold, min_window, max_window));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_strategyr_bbands_cpp", (DL_FUNC) &_strategyr_bbands_cpp, 3},
    {"_strategyr_bbands_cpp2", (DL_FUNC) &_strategyr_bbands_cpp2, 3},
    {"_strategyr_cluster_price_levels", (DL_FUNC) &_strategyr_cluster_price_levels, 4},
    {"_strategyr_merge_overlapping_zones", (DL_FUNC) &_strategyr_merge_overlapping_zones, 6},
    {"_strategyr_detect_cycles_now_cpp", (DL_FUNC) &_strategyr_detect_cycles_now_cpp, 3},
    {"_strategyr_detect_main_cycles_cpp", (DL_FUNC) &_strategyr_detect_main_cycles_cpp, 4},
    {"_strategyr_get_now_fresh_main_cycles_cpp", (DL_FUNC) &_strategyr_get_now_fresh_main_cycles_cpp, 3},
    {"_strategyr_twoline_cross", (DL_FUNC) &_strategyr_twoline_cross, 2},
    {"_strategyr_event_score", (DL_FUNC) &_strategyr_event_score, 4},
    {"_strategyr_fib_all_cpp", (DL_FUNC) &_strategyr_fib_all_cpp, 4},
    {"_strategyr_get_fib_ladder_index_cpp", (DL_FUNC) &_strategyr_get_fib_ladder_index_cpp, 4},
    {"_strategyr_detect_pivots_cpp", (DL_FUNC) &_strategyr_detect_pivots_cpp, 7},
    {"_strategyr_rolling_sum", (DL_FUNC) &_strategyr_rolling_sum, 2},
    {"_strategyr_rolling_mean", (DL_FUNC) &_strategyr_rolling_mean, 2},
    {"_strategyr_rolling_sd", (DL_FUNC) &_strategyr_rolling_sd, 3},
    {"_strategyr_ema_ttr_fixed_step", (DL_FUNC) &_strategyr_ema_ttr_fixed_step, 3},
    {"_strategyr_ema_tau_fixed_step", (DL_FUNC) &_strategyr_ema_tau_fixed_step, 2},
    {"_strategyr_ema_tau_irregular", (DL_FUNC) &_strategyr_ema_tau_irregular, 3},
    {"_strategyr_zones_quantile_fixed_cpp", (DL_FUNC) &_strategyr_zones_quantile_fixed_cpp, 3},
    {"_strategyr_zones_quantile_dyn_cpp", (DL_FUNC) &_strategyr_zones_quantile_dyn_cpp, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_strategyr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
