// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// atr_cpp
NumericVector atr_cpp(NumericVector high, NumericVector low, NumericVector close, int n);
RcppExport SEXP _strategyr_atr_cpp(SEXP highSEXP, SEXP lowSEXP, SEXP closeSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type high(highSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type low(lowSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type close(closeSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(atr_cpp(high, low, close, n));
    return rcpp_result_gen;
END_RCPP
}
// atr_cpp2
NumericVector atr_cpp2(NumericVector high, NumericVector low, NumericVector close, int n);
RcppExport SEXP _strategyr_atr_cpp2(SEXP highSEXP, SEXP lowSEXP, SEXP closeSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type high(highSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type low(lowSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type close(closeSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(atr_cpp2(high, low, close, n));
    return rcpp_result_gen;
END_RCPP
}
// bbands_cpp
List bbands_cpp(NumericVector x, int n, double sd);
RcppExport SEXP _strategyr_bbands_cpp(SEXP xSEXP, SEXP nSEXP, SEXP sdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type sd(sdSEXP);
    rcpp_result_gen = Rcpp::wrap(bbands_cpp(x, n, sd));
    return rcpp_result_gen;
END_RCPP
}
// bbands_cpp2
List bbands_cpp2(NumericVector x, int n, double sd);
RcppExport SEXP _strategyr_bbands_cpp2(SEXP xSEXP, SEXP nSEXP, SEXP sdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type sd(sdSEXP);
    rcpp_result_gen = Rcpp::wrap(bbands_cpp2(x, n, sd));
    return rcpp_result_gen;
END_RCPP
}
// get_now_cycles_cpp
DataFrame get_now_cycles_cpp(const DataFrame& pivots, int min_backward_bars, int min_stable_pivots);
RcppExport SEXP _strategyr_get_now_cycles_cpp(SEXP pivotsSEXP, SEXP min_backward_barsSEXP, SEXP min_stable_pivotsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const DataFrame& >::type pivots(pivotsSEXP);
    Rcpp::traits::input_parameter< int >::type min_backward_bars(min_backward_barsSEXP);
    Rcpp::traits::input_parameter< int >::type min_stable_pivots(min_stable_pivotsSEXP);
    rcpp_result_gen = Rcpp::wrap(get_now_cycles_cpp(pivots, min_backward_bars, min_stable_pivots));
    return rcpp_result_gen;
END_RCPP
}
// get_bt_cycles_cpp
List get_bt_cycles_cpp(IntegerVector idx, NumericVector price, NumericVector datetime, int cycle_N);
RcppExport SEXP _strategyr_get_bt_cycles_cpp(SEXP idxSEXP, SEXP priceSEXP, SEXP datetimeSEXP, SEXP cycle_NSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type idx(idxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type price(priceSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type datetime(datetimeSEXP);
    Rcpp::traits::input_parameter< int >::type cycle_N(cycle_NSEXP);
    rcpp_result_gen = Rcpp::wrap(get_bt_cycles_cpp(idx, price, datetime, cycle_N));
    return rcpp_result_gen;
END_RCPP
}
// get_now_fresh_main_cycles_cpp
DataFrame get_now_fresh_main_cycles_cpp(const DataFrame& pivots, int min_backward_bars, int min_stable_pivots);
RcppExport SEXP _strategyr_get_now_fresh_main_cycles_cpp(SEXP pivotsSEXP, SEXP min_backward_barsSEXP, SEXP min_stable_pivotsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const DataFrame& >::type pivots(pivotsSEXP);
    Rcpp::traits::input_parameter< int >::type min_backward_bars(min_backward_barsSEXP);
    Rcpp::traits::input_parameter< int >::type min_stable_pivots(min_stable_pivotsSEXP);
    rcpp_result_gen = Rcpp::wrap(get_now_fresh_main_cycles_cpp(pivots, min_backward_bars, min_stable_pivots));
    return rcpp_result_gen;
END_RCPP
}
// ema_cpp
NumericVector ema_cpp(NumericVector x, int n);
RcppExport SEXP _strategyr_ema_cpp(SEXP xSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(ema_cpp(x, n));
    return rcpp_result_gen;
END_RCPP
}
// ema_cpp2
NumericVector ema_cpp2(NumericVector x, int n);
RcppExport SEXP _strategyr_ema_cpp2(SEXP xSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(ema_cpp2(x, n));
    return rcpp_result_gen;
END_RCPP
}
// ema_metrics_cpp
DataFrame ema_metrics_cpp(NumericVector ema_fast, NumericVector ema_slow, int slope_window, int rolling_window, double eps);
RcppExport SEXP _strategyr_ema_metrics_cpp(SEXP ema_fastSEXP, SEXP ema_slowSEXP, SEXP slope_windowSEXP, SEXP rolling_windowSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type ema_fast(ema_fastSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ema_slow(ema_slowSEXP);
    Rcpp::traits::input_parameter< int >::type slope_window(slope_windowSEXP);
    Rcpp::traits::input_parameter< int >::type rolling_window(rolling_windowSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(ema_metrics_cpp(ema_fast, ema_slow, slope_window, rolling_window, eps));
    return rcpp_result_gen;
END_RCPP
}
// fib_all_cpp
List fib_all_cpp(double trend_start, double trend_end, NumericVector retr_levels, NumericVector ext_levels);
RcppExport SEXP _strategyr_fib_all_cpp(SEXP trend_startSEXP, SEXP trend_endSEXP, SEXP retr_levelsSEXP, SEXP ext_levelsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type trend_start(trend_startSEXP);
    Rcpp::traits::input_parameter< double >::type trend_end(trend_endSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type retr_levels(retr_levelsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ext_levels(ext_levelsSEXP);
    rcpp_result_gen = Rcpp::wrap(fib_all_cpp(trend_start, trend_end, retr_levels, ext_levels));
    return rcpp_result_gen;
END_RCPP
}
// fib_all_vec_cpp
Rcpp::NumericMatrix fib_all_vec_cpp(const Rcpp::NumericVector& bg, const Rcpp::NumericVector& ed);
RcppExport SEXP _strategyr_fib_all_vec_cpp(SEXP bgSEXP, SEXP edSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type bg(bgSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type ed(edSEXP);
    rcpp_result_gen = Rcpp::wrap(fib_all_vec_cpp(bg, ed));
    return rcpp_result_gen;
END_RCPP
}
// get_fib_ladder_index_cpp
Rcpp::IntegerVector get_fib_ladder_index_cpp(const Rcpp::NumericVector& close, const Rcpp::NumericVector& bg, const Rcpp::NumericVector& ed, int center_idx);
RcppExport SEXP _strategyr_get_fib_ladder_index_cpp(SEXP closeSEXP, SEXP bgSEXP, SEXP edSEXP, SEXP center_idxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type close(closeSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type bg(bgSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type ed(edSEXP);
    Rcpp::traits::input_parameter< int >::type center_idx(center_idxSEXP);
    rcpp_result_gen = Rcpp::wrap(get_fib_ladder_index_cpp(close, bg, ed, center_idx));
    return rcpp_result_gen;
END_RCPP
}
// pivots_cpp_slow
DataFrame pivots_cpp_slow(NumericVector high, NumericVector low, int span);
RcppExport SEXP _strategyr_pivots_cpp_slow(SEXP highSEXP, SEXP lowSEXP, SEXP spanSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type high(highSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type low(lowSEXP);
    Rcpp::traits::input_parameter< int >::type span(spanSEXP);
    rcpp_result_gen = Rcpp::wrap(pivots_cpp_slow(high, low, span));
    return rcpp_result_gen;
END_RCPP
}
// pivots_cpp
DataFrame pivots_cpp(NumericVector high, NumericVector low, int span);
RcppExport SEXP _strategyr_pivots_cpp(SEXP highSEXP, SEXP lowSEXP, SEXP spanSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type high(highSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type low(lowSEXP);
    Rcpp::traits::input_parameter< int >::type span(spanSEXP);
    rcpp_result_gen = Rcpp::wrap(pivots_cpp(high, low, span));
    return rcpp_result_gen;
END_RCPP
}
// zones_pivots_cpp
DataFrame zones_pivots_cpp(NumericVector high, NumericVector low, NumericVector atr, int span, int k, double tol_mult);
RcppExport SEXP _strategyr_zones_pivots_cpp(SEXP highSEXP, SEXP lowSEXP, SEXP atrSEXP, SEXP spanSEXP, SEXP kSEXP, SEXP tol_multSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type high(highSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type low(lowSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type atr(atrSEXP);
    Rcpp::traits::input_parameter< int >::type span(spanSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< double >::type tol_mult(tol_multSEXP);
    rcpp_result_gen = Rcpp::wrap(zones_pivots_cpp(high, low, atr, span, k, tol_mult));
    return rcpp_result_gen;
END_RCPP
}
// get_now_pivots_cpp
DataFrame get_now_pivots_cpp(const NumericVector& high, const NumericVector& low, const NumericVector& datetime, int span, Rcpp::Nullable<int> latest_n, bool refined, double min_swing);
RcppExport SEXP _strategyr_get_now_pivots_cpp(SEXP highSEXP, SEXP lowSEXP, SEXP datetimeSEXP, SEXP spanSEXP, SEXP latest_nSEXP, SEXP refinedSEXP, SEXP min_swingSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type high(highSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type low(lowSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type datetime(datetimeSEXP);
    Rcpp::traits::input_parameter< int >::type span(spanSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<int> >::type latest_n(latest_nSEXP);
    Rcpp::traits::input_parameter< bool >::type refined(refinedSEXP);
    Rcpp::traits::input_parameter< double >::type min_swing(min_swingSEXP);
    rcpp_result_gen = Rcpp::wrap(get_now_pivots_cpp(high, low, datetime, span, latest_n, refined, min_swing));
    return rcpp_result_gen;
END_RCPP
}
// rsi_cpp
NumericVector rsi_cpp(NumericVector price, int n);
RcppExport SEXP _strategyr_rsi_cpp(SEXP priceSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type price(priceSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(rsi_cpp(price, n));
    return rcpp_result_gen;
END_RCPP
}
// sma_cpp
NumericVector sma_cpp(NumericVector x, int n);
RcppExport SEXP _strategyr_sma_cpp(SEXP xSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(sma_cpp(x, n));
    return rcpp_result_gen;
END_RCPP
}
// zones_quantile_fixed_cpp
DataFrame zones_quantile_fixed_cpp(NumericVector high, NumericVector low, int window);
RcppExport SEXP _strategyr_zones_quantile_fixed_cpp(SEXP highSEXP, SEXP lowSEXP, SEXP windowSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type high(highSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type low(lowSEXP);
    Rcpp::traits::input_parameter< int >::type window(windowSEXP);
    rcpp_result_gen = Rcpp::wrap(zones_quantile_fixed_cpp(high, low, window));
    return rcpp_result_gen;
END_RCPP
}
// zones_quantile_dyn_cpp
DataFrame zones_quantile_dyn_cpp(NumericVector high, NumericVector low, NumericVector close, NumericVector atr14, double mom_threshold, int min_window, int max_window);
RcppExport SEXP _strategyr_zones_quantile_dyn_cpp(SEXP highSEXP, SEXP lowSEXP, SEXP closeSEXP, SEXP atr14SEXP, SEXP mom_thresholdSEXP, SEXP min_windowSEXP, SEXP max_windowSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type high(highSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type low(lowSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type close(closeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type atr14(atr14SEXP);
    Rcpp::traits::input_parameter< double >::type mom_threshold(mom_thresholdSEXP);
    Rcpp::traits::input_parameter< int >::type min_window(min_windowSEXP);
    Rcpp::traits::input_parameter< int >::type max_window(max_windowSEXP);
    rcpp_result_gen = Rcpp::wrap(zones_quantile_dyn_cpp(high, low, close, atr14, mom_threshold, min_window, max_window));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_strategyr_atr_cpp", (DL_FUNC) &_strategyr_atr_cpp, 4},
    {"_strategyr_atr_cpp2", (DL_FUNC) &_strategyr_atr_cpp2, 4},
    {"_strategyr_bbands_cpp", (DL_FUNC) &_strategyr_bbands_cpp, 3},
    {"_strategyr_bbands_cpp2", (DL_FUNC) &_strategyr_bbands_cpp2, 3},
    {"_strategyr_get_now_cycles_cpp", (DL_FUNC) &_strategyr_get_now_cycles_cpp, 3},
    {"_strategyr_get_bt_cycles_cpp", (DL_FUNC) &_strategyr_get_bt_cycles_cpp, 4},
    {"_strategyr_get_now_fresh_main_cycles_cpp", (DL_FUNC) &_strategyr_get_now_fresh_main_cycles_cpp, 3},
    {"_strategyr_ema_cpp", (DL_FUNC) &_strategyr_ema_cpp, 2},
    {"_strategyr_ema_cpp2", (DL_FUNC) &_strategyr_ema_cpp2, 2},
    {"_strategyr_ema_metrics_cpp", (DL_FUNC) &_strategyr_ema_metrics_cpp, 5},
    {"_strategyr_fib_all_cpp", (DL_FUNC) &_strategyr_fib_all_cpp, 4},
    {"_strategyr_fib_all_vec_cpp", (DL_FUNC) &_strategyr_fib_all_vec_cpp, 2},
    {"_strategyr_get_fib_ladder_index_cpp", (DL_FUNC) &_strategyr_get_fib_ladder_index_cpp, 4},
    {"_strategyr_pivots_cpp_slow", (DL_FUNC) &_strategyr_pivots_cpp_slow, 3},
    {"_strategyr_pivots_cpp", (DL_FUNC) &_strategyr_pivots_cpp, 3},
    {"_strategyr_zones_pivots_cpp", (DL_FUNC) &_strategyr_zones_pivots_cpp, 6},
    {"_strategyr_get_now_pivots_cpp", (DL_FUNC) &_strategyr_get_now_pivots_cpp, 7},
    {"_strategyr_rsi_cpp", (DL_FUNC) &_strategyr_rsi_cpp, 2},
    {"_strategyr_sma_cpp", (DL_FUNC) &_strategyr_sma_cpp, 2},
    {"_strategyr_zones_quantile_fixed_cpp", (DL_FUNC) &_strategyr_zones_quantile_fixed_cpp, 3},
    {"_strategyr_zones_quantile_dyn_cpp", (DL_FUNC) &_strategyr_zones_quantile_dyn_cpp, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_strategyr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
