#include <Rcpp.h>
#include <cmath>

// detect event function
// calculate backtest performance
// backtest performance becomes an indicator
// pos is different; pos is vector generated by a strategy
// when we are doing backtest of event, it is a binary pos for single event
// so you will classify it into events of certain days after bullish/bearish cross
// or you can map atr into bins; then you can provide a combination of last several bins; you will have thousand of types of events here; so be careful to choose suitable event classifications

// you also need to discuss the standard format of DT (datetime, open, high, low, close)
// Exponential Moving Average (EMA)
//
// EMA extends the simple moving average (SMA) by assigning exponentially
// decaying weights to past observations. Newer values receive higher weight
// through a decay parameter alpha, where 0 < alpha <= 1.
//
// The recursive definition is:
//   ema_t = alpha * x_t + (1 - alpha) * ema_{t-1}
//
// As a result, EMA is an autocorrelated time series and requires an initial
// seed value. Different seeding strategies lead to different early behavior.
//
// Relationship to SMA and time-series models:
//   - SMA is a finite-window MA(n) process.
//   - EMA corresponds to an infinite-memory AR(1)-type filter with decay
//     governed by alpha.
//
// Seeding options:
//   - seed_mode = 0: seed using SMA(n), with NA padding before index (n - 1).
//     This matches the default behavior of TTR::EMA.
//   - seed_mode = 1: seed using the first observation x[0], producing no
//     leading NA values.
//
// By default, technical analysis libraries use:
//   alpha = 2 / (n + 1)
// which is recommended for comparability with common TA tools.
//
// Alternative choices of alpha are also supported, including:
//   - Wilder’s smoothing: alpha = 1 / n (used for RSI, ATR, ADX)
//   - Half-life formulation: alpha = 1 - exp(-log(2) / half_life),
//     where half_life is a chosen number of steps for the EMA weight to decay by 50%
//   - Time-constant formulation: alpha = 1 - exp(-1 / tau),
//     where tau is a chosen continuous-time decay constant
//
// As with SMA, the EMA value at index i is defined only after x[i] is observed.
// The handling of early values depends on the chosen seeding strategy.

// Strategyr package is for generating strategy order for Stocks, Bonds, Derivatives, and Crypto assets;
// This needs to be moved to a header part; so we can reuse this function in the future
// It is suggested to have a .h file including ema_core/ema_cpp also; but be careful not to put too many nuances in rcpp part and unseen by R users
// And I don't think we need to let RCPP overdoing its job if data.table and plain R vector computation can achieve the same purpose without sacrificing too much efficiency
// we are not simply replicating a TA package because we view all the indicators an outcome of certain strategy's weighted backtesting output
// Thus it allows our package to have a very unique perspective of all the measures and have more innovative indicators
// Our package will have event class of measures, which are binary variables different from indicator and position; through a normal post-event test, we can see the statitics of strategy of holding a position linked to the event for different periods; it is an intermediate outcome for evaluation; it is part of the workflow of horning strategy orders
// pos_ family generates vector position over time, which is convenient for vector-type fast backtesting (not a simulation backtesting), so it is also not our final output
// ord_ and portf_ families are the final outputs of this package; the former determines what postion and weight of allocated budget for certain security in current moment; the latter is for determine the optimal weights across assets

// all rcpp functions should only use past information, so they can also be used in live trading


// struct
struct ema_cross_state {
  int trend_cycle = 0;              // 1 if fast > slow, -1 if fast < slow, 0 if fast == slow
  int cross_type  = 0;              // 1 up, -1 down, 0 none yet
  int cross_age   = NA_INTEGER;     // 0 freshest; NA only when no cross yet
  int atr_ok_on_age  = NA_INTEGER;  // first cross_age where ATR condition is satisfied
  int atr_ok_off_age = NA_INTEGER;  // first cross_age where ATR condition stops being satisfied (after it was satisfied)
  double p0 = NA_REAL;              // inception price at last cross bar
  double max_ir = 0.0;              // max inception return since cross start
  double min_ir = 0.0;              // min inception return since cross start
};

// [[Rcpp::export]]
Rcpp::DataFrame twoline_cross(const Rcpp::NumericVector& fast_line,
                             const Rcpp::NumericVector& slow_line,
                             const Rcpp::NumericVector& price,
                             const Rcpp::LogicalVector& atr_ok)
{
  const int n = fast_line.size();
  if (slow_line.size() != n || price.size() != n || atr_ok.size() != n) {
    Rcpp::stop("input vectors must have the same length.");
  }
  if (n == 0) return Rcpp::DataFrame::create();

  // outputs
  Rcpp::IntegerVector out_cross_type(n, 0);
  Rcpp::IntegerVector out_cross_age(n, NA_INTEGER);
  Rcpp::NumericVector out_max_ir(n, NA_REAL);
  Rcpp::NumericVector out_min_ir(n, NA_REAL);
  Rcpp::IntegerVector out_atr_on_age(n, NA_INTEGER);
  Rcpp::IntegerVector out_atr_off_age(n, NA_INTEGER);

  ema_cross_state st;

  // update as a lambda (legal inside function)
  auto update = [&](ema_cross_state& st, double fast, double slow, double px, bool atr) {

    const int trend = (fast > slow) ? 1 : ((fast < slow) ? -1 : 0);

    // initial "all zero" / "pre-cycle" period
    if (trend == 0 && st.trend_cycle == 0) {
      return;
    }

    // first non-flat cycle begins: establish direction, but no cross possible yet
    if (trend != 0 && st.trend_cycle == 0) {
      st.trend_cycle = trend;
      // keep cross_type = 0, cross_age = NA
      return;
    }

    // cross to new cycle: sign flip between previous trend_cycle and current trend
    if (trend != 0 && st.trend_cycle * trend == -1) {
      st.trend_cycle = trend;
      st.cross_type  = (trend > 0) ? 1 : -1;
      st.cross_age   = 0;

      st.atr_ok_on_age  = atr ? 0 : NA_INTEGER;
      st.atr_ok_off_age = NA_INTEGER;

      st.p0 = px;
      st.max_ir = 0.0;
      st.min_ir = 0.0;
      return;
    }

    // staying in same cycle OR flat-touch inside an established cycle
    // (trend == 0 && st.trend_cycle != 0) OR (trend != 0 && st.trend_cycle * trend == 1)

    // only update ages/IR once a cross has happened (exclude the first ever cycle)
    if (st.cross_type != 0) {
      st.cross_age = (st.cross_age == NA_INTEGER) ? NA_INTEGER : (st.cross_age + 1);

      // ATR on/off ages (first time only)
      if (st.atr_ok_on_age == NA_INTEGER) {
        if (atr) st.atr_ok_on_age = st.cross_age;
      } else if (st.atr_ok_off_age == NA_INTEGER) {
        if (!atr) st.atr_ok_off_age = st.cross_age;
      }

      // inception return since p0
      // (p0 should never be NA here, but guard anyway)
      if (!Rcpp::NumericVector::is_na(st.p0) && st.p0 != 0.0) {
        const double ir = px / st.p0 - 1.0;
        if (ir > st.max_ir) st.max_ir = ir;
        if (ir < st.min_ir) st.min_ir = ir;
      }
    }
  };

  for (int i = 0; i < n; ++i) {
    const double fast = fast_line[i];
    const double slow = slow_line[i];
    const double px   = price[i];

    // guarantee no NA reaches here; enforce it
    if (Rcpp::NumericVector::is_na(fast) ||
        Rcpp::NumericVector::is_na(slow) ||
        Rcpp::NumericVector::is_na(px)   ||
        Rcpp::LogicalVector::is_na(atr_ok[i])) {
					Rcpp::stop("na values are not allowed (fast/slow/price/atr_ok).");
					// continue;
    }

    const bool atr = (atr_ok[i] == TRUE);

    update(st, fast, slow, px, atr);

    // write outputs every bar (stateful -> stateless annotation)
    out_cross_type[i] = st.cross_type;
    out_cross_age[i]  = st.cross_age;
    out_max_ir[i]     = (st.cross_type != 0) ? st.max_ir : NA_REAL;
    out_min_ir[i]     = (st.cross_type != 0) ? st.min_ir : NA_REAL;
    out_atr_on_age[i]  = st.atr_ok_on_age;
    out_atr_off_age[i] = st.atr_ok_off_age;
  }

  return Rcpp::DataFrame::create(
    Rcpp::Named("cross_type")      = out_cross_type,
    Rcpp::Named("cross_age")       = out_cross_age,
    Rcpp::Named("max_ir")          = out_max_ir,
    Rcpp::Named("min_ir")          = out_min_ir,
    Rcpp::Named("atr_ok_on_age")   = out_atr_on_age,
    Rcpp::Named("atr_ok_off_age")  = out_atr_off_age
  );
}
