# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

atr_cpp <- function(high, low, close, n) {
    .Call(`_strategyr_atr_cpp`, high, low, close, n)
}

atr_cpp2 <- function(high, low, close, n) {
    .Call(`_strategyr_atr_cpp2`, high, low, close, n)
}

bbands_cpp <- function(x, n = 20L, sd = 2.0) {
    .Call(`_strategyr_bbands_cpp`, x, n, sd)
}

bbands_cpp2 <- function(x, n = 20L, sd = 2.0) {
    .Call(`_strategyr_bbands_cpp2`, x, n, sd)
}

get_now_cycles_cpp <- function(pivots, min_backward_bars = 360L, min_stable_pivots = 7L) {
    .Call(`_strategyr_get_now_cycles_cpp`, pivots, min_backward_bars, min_stable_pivots)
}

get_now_fresh_main_cycles_cpp <- function(pivots, min_backward_bars = 360L, min_stable_pivots = 7L) {
    .Call(`_strategyr_get_now_fresh_main_cycles_cpp`, pivots, min_backward_bars, min_stable_pivots)
}

ema_cpp <- function(x, n) {
    .Call(`_strategyr_ema_cpp`, x, n)
}

ema_cpp2 <- function(x, n) {
    .Call(`_strategyr_ema_cpp2`, x, n)
}

ema_metrics_cpp <- function(ema_fast, ema_slow, slope_window = 3L, rolling_window = 200L, eps = 1e-6) {
    .Call(`_strategyr_ema_metrics_cpp`, ema_fast, ema_slow, slope_window, rolling_window, eps)
}

fib_all_cpp <- function(trend_start, trend_end, retr_levels = as.numeric( c(0.0, 0.236, 0.382, 0.5, 0.618, 0.786, 1.0)), ext_levels = as.numeric( c(0.272, 0.618, 1.0, 1.272, 1.618, 2.0))) {
    .Call(`_strategyr_fib_all_cpp`, trend_start, trend_end, retr_levels, ext_levels)
}

fib_all_vec_cpp <- function(bg, ed) {
    .Call(`_strategyr_fib_all_vec_cpp`, bg, ed)
}

get_now_pivots_cpp <- function(high, low, datetime, span = 3L, latest_n = NULL, refined = TRUE, min_swing = 0.05) {
    .Call(`_strategyr_get_now_pivots_cpp`, high, low, datetime, span, latest_n, refined, min_swing)
}

rsi_cpp <- function(price, n = 14L) {
    .Call(`_strategyr_rsi_cpp`, price, n)
}

sma_cpp <- function(x, n) {
    .Call(`_strategyr_sma_cpp`, x, n)
}

pivots_cpp <- function(high, low, span = 5L) {
    .Call(`_strategyr_pivots_cpp`, high, low, span)
}

zones_pivots_cpp <- function(high, low, atr, span = 2L, k = 6L, tol_mult = 0.15) {
    .Call(`_strategyr_zones_pivots_cpp`, high, low, atr, span, k, tol_mult)
}

zones_quantile_fixed_cpp <- function(high, low, window = 20L) {
    .Call(`_strategyr_zones_quantile_fixed_cpp`, high, low, window)
}

zones_quantile_dyn_cpp <- function(high, low, close, atr14, mom_threshold = 0.015, min_window = 20L, max_window = 120L) {
    .Call(`_strategyr_zones_quantile_dyn_cpp`, high, low, close, atr14, mom_threshold, min_window, max_window)
}

