# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gen_action_plan_rcpp <- function(ctr_size, ctr_step, lev, last_px, ctr_unit, avg_price, cash, tgt_pos, tol_pos, strat_id, pos_dir = 0L) {
    .Call(`_strategyr_gen_action_plan_rcpp`, ctr_size, ctr_step, lev, last_px, ctr_unit, avg_price, cash, tgt_pos, tol_pos, strat_id, pos_dir)
}

backtest_rcpp <- function(timestamp, open, high, low, close, tgt_pos, pos_strat, tol_pos, strat, asset, ctr_size = 1.0, ctr_step = 1.0, lev = 10.0, fee_rt = 0.0, fund_rt = 0.0, rec = FALSE) {
    .Call(`_strategyr_backtest_rcpp`, timestamp, open, high, low, close, tgt_pos, pos_strat, tol_pos, strat, asset, ctr_size, ctr_step, lev, fee_rt, fund_rt, rec)
}

detect_cycles_now_cpp <- function(pivots, min_backward_bars = 360L, min_stable_pivots = 7L) {
    .Call(`_strategyr_detect_cycles_now_cpp`, pivots, min_backward_bars, min_stable_pivots)
}

detect_main_cycles_cpp <- function(idx, price, datetime, cycle_N) {
    .Call(`_strategyr_detect_main_cycles_cpp`, idx, price, datetime, cycle_N)
}

get_now_fresh_main_cycles_cpp <- function(pivots, min_backward_bars = 360L, min_stable_pivots = 7L) {
    .Call(`_strategyr_get_now_fresh_main_cycles_cpp`, pivots, min_backward_bars, min_stable_pivots)
}

ema_ttr_fixed_step <- function(x, n, wilder = FALSE) {
    .Call(`_strategyr_ema_ttr_fixed_step`, x, n, wilder)
}

ema_fixed_step_tau <- function(x, tau) {
    .Call(`_strategyr_ema_fixed_step_tau`, x, tau)
}

ema_tau_irregular <- function(x, t, tau) {
    .Call(`_strategyr_ema_tau_irregular`, x, t, tau)
}

twoline_cross <- function(fast_line, slow_line, price, atr_ok) {
    .Call(`_strategyr_twoline_cross`, fast_line, slow_line, price, atr_ok)
}

fib_all_cpp <- function(trend_start, trend_end, retr_levels = as.numeric( c(0.0, 0.236, 0.382, 0.5, 0.618, 0.786, 1.0)), ext_levels = as.numeric( c(0.272, 0.618, 1.0, 1.272, 1.618, 2.0))) {
    .Call(`_strategyr_fib_all_cpp`, trend_start, trend_end, retr_levels, ext_levels)
}

get_fib_ladder_index_cpp <- function(close, bg, ed, center_idx = 9L) {
    .Call(`_strategyr_get_fib_ladder_index_cpp`, close, bg, ed, center_idx)
}

detect_pivots_cpp <- function(high, low, datetime, span = 3L, latest_n = NULL, refined = TRUE, min_swing = 0.05) {
    .Call(`_strategyr_detect_pivots_cpp`, high, low, datetime, span, latest_n, refined, min_swing)
}

rolling_mean <- function(x, n) {
    .Call(`_strategyr_rolling_mean`, x, n)
}

rolling_sum <- function(x, n) {
    .Call(`_strategyr_rolling_sum`, x, n)
}

rolling_sd <- function(x, n, sample = FALSE) {
    .Call(`_strategyr_rolling_sd`, x, n, sample)
}

rolling_mean_abs_dev <- function(x, n) {
    .Call(`_strategyr_rolling_mean_abs_dev`, x, n)
}

rolling_wma <- function(x, n) {
    .Call(`_strategyr_rolling_wma`, x, n)
}

rolling_max <- function(x, n) {
    .Call(`_strategyr_rolling_max`, x, n)
}

rolling_argmax_pct <- function(x, n) {
    .Call(`_strategyr_rolling_argmax_pct`, x, n)
}

rolling_min <- function(x, n) {
    .Call(`_strategyr_rolling_min`, x, n)
}

rolling_argmin_pct <- function(x, n) {
    .Call(`_strategyr_rolling_argmin_pct`, x, n)
}

rolling_quantiles <- function(x, n, probs) {
    .Call(`_strategyr_rolling_quantiles`, x, n, probs)
}

strat_buy_and_hold_rcpp <- function(timestamp) {
    .Call(`_strategyr_strat_buy_and_hold_rcpp`, timestamp)
}

strat_rsi_revert_signal_cpp <- function(rsi, oversold = 30.0, overbought = 70.0, exit_level = 50.0, target_size = 1.0) {
    .Call(`_strategyr_strat_rsi_revert_signal_cpp`, rsi, oversold, overbought, exit_level, target_size)
}

strat_donchian_turtle_signal_cpp <- function(close, entry_high, entry_low, exit_high, exit_low, target_size = 1.0) {
    .Call(`_strategyr_strat_donchian_turtle_signal_cpp`, close, entry_high, entry_low, exit_high, exit_low, target_size)
}

strat_atr_breakout_trailing_stop_signal_cpp <- function(close, atr, atr_mult = 1.0, trail_mult = 2.0, target_size = 1.0) {
    .Call(`_strategyr_strat_atr_breakout_trailing_stop_signal_cpp`, close, atr, atr_mult, trail_mult, target_size)
}

strat_pair_spread_revert_signal_cpp <- function(zscore_value, entry_z = 2.0, exit_z = 0.5, target_size = 1.0) {
    .Call(`_strategyr_strat_pair_spread_revert_signal_cpp`, zscore_value, entry_z, exit_z, target_size)
}

strat_rsi_divergence_signal_cpp <- function(close, rsi, pivot_left = 2L, pivot_right = 2L, exit_level = 50.0, target_size = 1.0) {
    .Call(`_strategyr_strat_rsi_divergence_signal_cpp`, close, rsi, pivot_left, pivot_right, exit_level, target_size)
}

backtest_portfolio_weights_core_cpp <- function(date_id, asset_id, open, close, target_weight, contract_size, initial_equity = 1.0, fee_rt = 0.0, rebalance_tol_weight = 0.0, n_assets = 0L) {
    .Call(`_strategyr_backtest_portfolio_weights_core_cpp`, date_id, asset_id, open, close, target_weight, contract_size, initial_equity, fee_rt, rebalance_tol_weight, n_assets)
}

aroon_up_pct_cpp <- function(high, n) {
    .Call(`_strategyr_aroon_up_pct_cpp`, high, n)
}

aroon_dn_pct_cpp <- function(low, n) {
    .Call(`_strategyr_aroon_dn_pct_cpp`, low, n)
}

sar_cpp <- function(high, low, accel) {
    .Call(`_strategyr_sar_cpp`, high, low, accel)
}
